# start from base
FROM ubuntu:r35
MAINTAINER Timothy Baker <tbaker8@luc.edu>

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

RUN mkdir umi_pipeline

RUN git clone https://github.com/sdparekh/zUMIs.git

RUN mv /zUMIs /umi_pipeline/zUMIs

WORKDIR /pipeline/FatFlies_scRNA

CMD ["python3", "scrna_configure_pipeline.py", "-z", "/umi_pipeline/zUMIs", "/pipeline/SampleSheet.csv"]
