# start from base
FROM ubuntu:r35
MAINTAINER Timothy Baker <tbaker8@luc.edu>

RUN mkdir pipeline

VOLUME ["/pipeline"]

WORKDIR /pipeline/FatFlies_scRNA

RUN python3 scrna_configure_pipeline.py -z /pipeline/zUMIs /pipeline/SampleSheet.csv
