# start from base
FROM ubuntu:18.04
MAINTAINER Timothy Baker <tbaker8@luc.edu>
# tag as scrna:ubuntu:18.04

# installing system package dependencies for various tools
RUN apt-get update && apt-get install -y \
  software-properties-common \
  dirmngr \
  apt-transport-https \
  lsb-release \
  ca-certificates \
  apt-utils \
  autoconf \
  automake \
  bash \
  curl \
  gcc \
  git \
  libbz2-dev \
  liblzma-dev \
  libcurl4-gnutls-dev \
  libssl-dev \
  make \
  perl \
  pigz \
  unzip \
  wget \
  zip \
  zlib1g-dev \
  default-jre


# Installing python on ubuntu
COPY requirements.txt /tmp
RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y \
  python3 \
  python3-pip \
  python3-dev && \
  ln -s /usr/bin/python3 /usr/local/bin/python3 && \
  python3 -m pip install -r /tmp/requirements.txt


# install STAR aligner
RUN \
  cd /usr/local/bin \
  && TARBALL=2.7.0f.tar.gz \
  && NAME=STAR-2.7.0f \
  && wget -P /usr/local/bin/star https://github.com/alexdobin/STAR/archive/${TARBALL} \
  && tar -xzf /usr/local/bin/star/${TARBALL} -C /usr/local/bin/star \
  && make -C /usr/local/bin/star/${NAME}/source STAR \
  && cd /



# Need to make sure JAVA installed correctly
# FastQC
RUN \
  URL=http://www.bioinformatics.babraham.ac.uk/projects/fastqc \
  && VER=0.11.8 \
  && NAME=fastqc_v${VER} \
  && mkdir -p /fastqc_tmp/ \
  && wget -O /fastqc_tmp/${NAME}.zip ${URL}/${NAME}.zip \
  && unzip /fastqc_tmp/${NAME}.zip -d /fastqc_tmp/ \
  && chmod -R 755 /fastqc_tmp/ \
  && ln -s /fastqc_tmp/FastQC/fastqc /usr/local/bin/fastqc \
  && rm -rf /fastqc_tmp/${NAME}.zip \
  && cd /


# install htslib 1.9
RUN \
  URL=https://github.com/samtools/htslib/releases/download \
  && VER=1.9 \
  && NAME=htslib-${VER} \
  && TARBALL=${NAME}.tar.bz2 \
  && wget -cP /usr/local/bin/htslib ${URL}/${VER}/${TARBALL} \
  && tar -vxjf /usr/local/bin/htslib/${TARBALL} -C /usr/local/bin/htslib \
  && autoreconf \
  && ./configure \
  && make \
  && make install \
  && cd /


# installing samtools 1.9
RUN \
  URL=https://github.com/samtools/samtools/releases/download \
  && VER=1.9 \
  && NAME=samtools-${VER} \
  && TARBALL=${NAME}.tar.bz2 \
  && wget -cP /usr/local/bin/samtools ${URL}/${VER}/${TARBALL} \
  && tar -vxjf /usr/local/bin/samtools/${TARBALL} -C /usr/local/bin/samtools \
  && make \
  && make install \
  && cd /
